---

server:
  port: 8780

spring:
  datasource:
    url: jdbc:hsqldb:mem:rentaltrucks
    username: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
