---

server:
  port: 8780

spring:
  datasource:
    url: jdbc:hsqldb:mem:rentaltrucks
    username: sa
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: hsql

---

spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgresql://localhost/rentaltrucks
    username: dwadden
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
